# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20170403_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='published_date',
        ),
        migrations.AddField(
            model_name='car',
            name='citympg',
            field=models.SmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='car',
            name='hwmpg',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.SmallIntegerField(default=2017),
        ),
    ]
