# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='make',
            name='make_display',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_make_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Make', to_field='make_display'),
        ),
    ]
