# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20170405_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
