# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20170405_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model_make_id',
            field=models.ForeignKey(db_column='make_display', on_delete=django.db.models.deletion.CASCADE, to='car.Make', to_field='make_display'),
        ),
    ]
