# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20170406_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='model_trim',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
